[project]
name = "xml-to-csv"
version = "0.1.0"
description = "Python tool to convert XML to CSV."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.2",
    "pandas>=2.3.3",
]
